"""added fullname

Revision ID: 75615034025e
Revises: 91a7fff23c65
Create Date: 2021-09-18 14:15:54.665231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75615034025e'
down_revision = '91a7fff23c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
